# Generated by Django 4.2.4 on 2023-09-02 15:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EFOterm",
            fields=[
                (
                    "efo_term_id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("term_name", models.CharField(max_length=255)),
                (
                    "synonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("parent_link", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="eoftermapp.efoterm",
                    ),
                ),
            ],
            options={
                "db_table": "efo_terms_app_efoterm",
            },
        ),
    ]
