# Generated by Django 4.2.4 on 2023-09-02 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eoftermapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="efoterm",
            table="efo_terms",
        ),
    ]
