# Generated by Django 4.2.4 on 2023-09-02 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eoftermapp", "0002_alter_efoterm_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="efoterm",
            table=None,
        ),
    ]
