# Generated by Django 4.2.4 on 2023-09-02 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eoftermapp", "0004_alter_efoterm_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EFOterm",
        ),
    ]
