# Generated by Django 4.2.4 on 2023-09-02 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eoftermapp", "0006_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EFOterm",
        ),
    ]
