# Generated by Django 4.2.4 on 2023-09-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eoftermapp", "0009_alter_efoterm_synonyms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="efoterm",
            name="efo_term_id",
            field=models.CharField(
                max_length=1000, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="efoterm",
            name="term_name",
            field=models.CharField(max_length=1000),
        ),
    ]
