# Generated by Django 4.2.4 on 2023-09-02 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eoftermapp", "0010_alter_efoterm_efo_term_id_alter_efoterm_term_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="efoterm",
            name="parent_link",
        ),
    ]
