# Generated by Django 4.2.4 on 2023-09-02 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eoftermapp", "0015_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EFOterm",
        ),
    ]
