# Generated by Django 4.2.4 on 2023-09-02 17:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("eoftermapp", "0016_delete_efoterm"),
    ]

    operations = [
        migrations.CreateModel(
            name="EFOterm",
            fields=[
                (
                    "efo_term_id",
                    models.CharField(
                        max_length=1000, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("term_name", models.CharField(max_length=1000)),
                (
                    "synonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1000),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "parents",
                    models.ManyToManyField(
                        blank=True, related_name="children", to="eoftermapp.efoterm"
                    ),
                ),
            ],
            options={
                "verbose_name": "EFO Term",
                "verbose_name_plural": "EFO Terms",
            },
        ),
    ]
