# Generated by Django 4.2.4 on 2023-09-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eoftermapp", "0017_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="efoterm",
            name="parents",
        ),
        migrations.CreateModel(
            name="ParentRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_relations",
                        to="eoftermapp.efoterm",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_relations",
                        to="eoftermapp.efoterm",
                    ),
                ),
            ],
        ),
    ]
