# Generated by Django 4.2.4 on 2023-09-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eoftermapp', '0018_remove_efoterm_parents_parentrelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentrelationship',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='parentrelationship',
            name='term',
        ),
        migrations.DeleteModel(
            name='EFOterm',
        ),
        migrations.DeleteModel(
            name='ParentRelationship',
        ),
    ]
