# Generated by Django 4.2.4 on 2023-09-05 08:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eoftermapp', '0019_remove_parentrelationship_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EFOterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efo_term_id', models.CharField(max_length=1000, unique=True)),
                ('term_name', models.CharField(max_length=1000)),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name': 'EFO Term',
                'verbose_name_plural': 'EFO Terms',
            },
        ),
        migrations.CreateModel(
            name='ParentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='eoftermapp.efoterm')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='eoftermapp.efoterm')),
            ],
        ),
    ]
